version: 2.1


jobs:
  build:
    working_directory: ~/project
    steps:
      - checkout

orbs:
  maven: circleci/maven@1.1.0

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
